import { withThemeByClassName } from "@storybook/addon-themes";
import type { Preview } from "@storybook/react-vite";
import { commonControlsExclude } from "../src/storybook/controls";
import "./generated/dark-theme-class.css";
import "./generated/light-theme-class.css";
import "./preview.css";

// The shipped stylesheet only switches theme via `prefers-color-scheme`
// (real apps have no manual toggle). These Storybook-only builds of the light
// and dark tokens are keyed off the theme classes, so the addon-themes toolbar
// and the accessibility matrix can preview either mode without depending on
// the OS setting. They are generated by the `style-dictionary.*-storybook.json`
// configs (see the `storybook`/`tokens:build` scripts) — never hand-edit them.
const storybookThemeDecorator = withThemeByClassName({
  themes: { light: "storybook-theme-light", dark: "storybook-theme-dark" },
  defaultTheme: import.meta.env.VITE_STORYBOOK_THEME === "dark" ? "dark" : "light",
});

const preview: Preview = {
  globalTypes: {
    theme: {
      description: "Preview color mode",
      toolbar: {
        icon: "circlehollow",
        items: ["light", "dark"],
        title: "Color mode",
        dynamicTitle: true,
      },
    },
  },
  initialGlobals: {
    theme: import.meta.env.VITE_STORYBOOK_THEME === "dark" ? "dark" : "light",
  },
  decorators: [storybookThemeDecorator],
  parameters: {
    layout: "centered",
    a11y: { test: "error" },
    controls: {
      exclude: commonControlsExclude,
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
      sort: "requiredFirst",
      expanded: true,
    },
    options: {
      storySort: {
        order: [
          "Audit",
          "Tokens",
          "Primitives",
          "Forms",
          "Feedback",
          "Filters",
          "Navigation",
          "Patterns",
          "Surfaces",
          "Layouts",
          "Motion",
          "Internal",
        ],
      },
    },
  },
};

export default preview;
