import { DecoratorHelpers } from "@storybook/addon-themes";
import type { Preview } from "@storybook/react-vite";
import { useLayoutEffect } from "react";
import { commonControlsExclude } from "../src/storybook/controls";
import "./generated/dark-theme-class.css";
import "./generated/light-theme-class.css";
import "./preview.css";

const THEME_CLASSES = { light: "storybook-theme-light", dark: "storybook-theme-dark" };
const DEFAULT_THEME = import.meta.env.VITE_STORYBOOK_THEME === "dark" ? "dark" : "light";

// The shipped stylesheet only switches theme via `prefers-color-scheme`
// (real apps have no manual toggle). These Storybook-only builds of the light
// and dark tokens are keyed off the theme classes, so the addon-themes toolbar
// and the accessibility matrix can preview either mode without depending on
// the OS setting. They are generated by the `style-dictionary.*-storybook.json`
// configs (see the `storybook`/`tokens:build` scripts) — never hand-edit them.
//
// Hand-rolled instead of addon-themes' `withThemeByClassName`: that helper
// swaps the class in a `useEffect`, which fires *after* the browser paints
// the previous theme's class once. Any element with `transition-colors` and
// an inherited (rather than explicitly-set) text color — e.g. the Button
// ghost variant — then animates from the old theme's color to the new one,
// and the a11y addon's scan can land mid-transition and report a false
// contrast violation. `useLayoutEffect` applies the class before paint, so
// there's no stale frame to animate from.
DecoratorHelpers.initializeThemeState(Object.keys(THEME_CLASSES), DEFAULT_THEME);
function storybookThemeDecorator(storyFn: () => unknown, context: Parameters<typeof DecoratorHelpers.pluckThemeFromContext>[0]) {
  const theme = DecoratorHelpers.pluckThemeFromContext(context) || DEFAULT_THEME;
  useLayoutEffect(() => {
    const root = document.documentElement;
    root.classList.remove(THEME_CLASSES.light, THEME_CLASSES.dark);
    root.classList.add(THEME_CLASSES[theme as keyof typeof THEME_CLASSES]);
  }, [theme]);
  return storyFn();
}

const preview: Preview = {
  initialGlobals: {
    theme: import.meta.env.VITE_STORYBOOK_THEME === "dark" ? "dark" : "light",
  },
  decorators: [storybookThemeDecorator],
  parameters: {
    layout: "centered",
    a11y: { test: "error" },
    controls: {
      exclude: commonControlsExclude,
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
      sort: "requiredFirst",
      expanded: true,
    },
    options: {
      storySort: {
        order: [
          "Audit",
          "Tokens",
          "Primitives",
          "Forms",
          "Feedback",
          "Filters",
          "Navigation",
          "Patterns",
          "Surfaces",
          "Layouts",
          "Motion",
          "Internal",
        ],
      },
    },
  },
};

export default preview;
